### ISSUE TITLE
App crashing on some video recording settings

### ISSUE THREAD

**Issue by aquatiko** [googleinterns/screen-latency-testing#10]
## Expected Behavior
The app should work with all video-recording settings in the first selector Activity.

## Actual Behavior
App crashes on some video-recording setting after pressing `START ANALYSIS` button.

## Steps to Reproduce the Problem

1. Install app on specified master version.
1. Try the end-to-end experiement using Server with all settings shown on selector activity.
1. The app will crash on some of the setting.

## Specifications

- Version: App based on commit 1a449d3be6ef1ea5d051b8d93e711cc491d14d25

**Comment by aquatiko** [comment]
The app crashes at this line:
https://github.com/googleinterns/screen-latency-testing/blob/1a449d3be6ef1ea5d051b8d93e711cc491d14d25/Camera2SlowMotion/app/src/main/java/com/example/android/camera2/slowmo/MainActivity.java#L116

**Comment by aquatiko** [comment]
Using a recording at `1920x1080p   120fps`:
In a 771 frame video file `mediaMetadataRetriever` can read frames 0-200 but it crashes on request to read frames from 0-250. viz. unexpected.

Using a recording at `1280x720p   120fps`:
In a 718 frame video file `mediaMetadataRetriever` can read frames 0-300 but it crashes on request to read frames from 0-400. viz. unexpected.

**Note:** Using `mediaMetadataRetriever` to read any valid individual frames works fine with crashing.
This makes the crashing of invalid frame read assumption false. The frames are saved correctly.
`SAFE_FRAMES` constant was addeded to prevent reading end frames keeping this assumption in mind but now the assumption is proved false.

**Comment by aquatiko** [comment]
Possible solutions could be:
- Making `SAFE_FRAMES` dynamic opposed to a constant to trim frame reads from end.
- Using low resolution images to avoid this issue to some extent. As seen in experiment above, lower resolution allows reading more images simultaneous.
- Read video frames in parts (or individually) and append to `frameList`.

**Comment by aquatiko** [comment]
**cc:** @mwarton @patrickmeiring

**Comment by mwarton** [comment]
Can you give some more details of the crash?  Is there an exception message?

**Comment by aquatiko** [comment]
I digged a bit deeper to find that the error points to this in `mediaMetadataRetriever` API
```java
if (!"yes".equals(extractMetadata(MediaMetadataRetriever.METADATA_KEY_HAS_VIDEO))) {
            throw new IllegalStateException("Does not contail video or image sequences");
        }
```
Surprisingly the video-files captured using high speed camera API dosen't come with 
`MediaMetadataRetriever.METADATA_KEY_HAS_VIDEO == "yes"`
instead it is
`MediaMetadataRetriever.METADATA_KEY_HAS_VIDEO == "null"`

**Comment by aquatiko** [comment]
Even these metadata fields are null as well
`MediaMetadataRetriever.METADATA_KEY_IMAGE_COUNT`
`MediaMetadataRetriever.METADATA_KEY_HAS_IMAGE`
`MediaMetadataRetriever.METADATA_KEY_VIDEO_FRAME_COUNT`
